name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Install Dependencies
        run: pnpm install

      - name: Fetch Tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Publish Tags
        run: node tag-releases.js
