name: Test Tag

on:
  push:
    tags:
      - '**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test tags
    runs-on: ubuntu-latest
    steps:
      - name: Do dummy
        run: echo "hello world!"
